# Site settings
title: The List powered by Creative Commons
email: info@creativecommons.org
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://thelist.creativecommons.org" # the base hostname & protocol for your site
twitter_username: creativecommons
github_username:  creativecommons

# Build settings
markdown: kramdown
